"resource/ui/ChangelogPanel.res"
{
	"ChangelogPanel"
	{
		"ControlName"		"CChangelogPanel"
		"fieldName"		"ChangelogPanel"
		"xpos"		"c-250"
		"ypos"		"c-125"
		"wide"		"450"
		"tall"		"300"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"settitlebarvisible"		"1"
		"title"		"#MOM_ChangeLog"
	}
	"ChangeLog"
	{
		"ControlName"		"RichText"
		"fieldName"		"ChangeLog"
		"xpos"		"12"
		"ypos"		"25"
		"wide"		"f24"
		"tall"		"f37"
		"AutoResize"		"3"
		"PinCorner"		"0" // PIN_TOPLEFT
        "PinnedCornerOffsetX" "12"
        "PinnedCornerOffsetY" "25"
        "UnpinnedCornerOffsetX" "-12"
        "UnpinnedCornerOffsetY" "-12"
        "proportionalToParent" "1"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"maxchars"		"-1"
		"scrollbar"		"1"
        "text" "Failed to load changelog!"
	}
}
