"resource/ui/Speedometer.res"
{
    "HudSpeedMeter"
    {
        "ControlName" "CHudSpeedMeter"
        "fieldName"   "HudSpeedMeter"
        "xpos"        "c-60"
        "ypos"        "c+65"
        "wide"        "120"
        "tall"        "60"
        "BgColor"     "Blank"
        "autoResize"  "0"
        "visible"     "1"
        "enabled"     "1"
    }
    "AbsSpeedometer"
    {
        "ControlName"   "SpeedometerLabel"
        "fieldName"     "AbsSpeedometer"
        "xpos"          "0"
        "ypos"          "0"
        "textAlignment" "center"
        "font"          "HudNumbersSmallBold"
        "FgColor"       "MOM.Speedometer.Normal"
        "wrap"          "0"
        "auto_tall_tocontents" "1"
        "auto_wide_tocontents" "1"
    }
    "HorizSpeedometer"
    {
        "ControlName"   "SpeedometerLabel"
        "fieldName"     "HorizSpeedometer"
        "xpos"          "0"
        "ypos"          "0"
        "textAlignment" "center"
        "font"          "HudNumbersSmallBold"
        "FgColor"       "MOM.Speedometer.Normal"
        "wrap"          "0"
        "auto_tall_tocontents" "1"
        "auto_wide_tocontents" "1"
    }
    "VertSpeedometer"
    {
        "ControlName"   "SpeedometerLabel"
        "fieldName"     "VertSpeedometer"
        "xpos"          "0"
        "ypos"          "0"
        "textAlignment" "center"
        "font"          "HudNumbersSmallBold"
        "FgColor"       "MOM.Speedometer.Normal"
        "wrap"          "0"
        "auto_tall_tocontents" "1"
        "auto_wide_tocontents" "1"
    }
    "LastJumpVelocity"
    {
        "ControlName"   "SpeedometerLabel"
        "fieldName"	    "LastJumpVelocity"
        "xpos"          "0"
        "ypos"          "0"
        "textAlignment" "center"
        "font"          "HudNumbersExtremelySmall"
        "FgColor"       "MOM.Speedometer.Normal"
        "wrap"          "0"
        "auto_tall_tocontents" "1"
        "auto_wide_tocontents" "1"
    }
    "StageEnterExitVelocity"
    {
        "ControlName"   "SpeedometerLabel"
        "fieldName"     "StageEnterExitVelocity"
        "xpos"          "0"
        "ypos"          "0"
        "textAlignment" "center"
        "font"          "HudNumbersExtremelySmall"
        "FgColor"       "MOM.Speedometer.Normal"
        "wrap"          "0"
        "auto_tall_tocontents" "1"
        "auto_wide_tocontents" "1"
    }
}